### ISSUE TITLE
つくる

### ISSUE THREAD

**Issue by matsumotius** [android-teamdev/vomage#1]
たぶん5/3くらいから作り始めます

**Comment by matsumotius** [comment]
### 決まってること
- 趣味チーム開発を試してみる（重要！）
- Androidアプリをつくる
- 数日程度で作れるものをテーマにする

### テーマ候補
- 画像単語帳
  - 英単語とそれを表す写真が出てきてイメージで覚えられる単語帳アプリ
- なにか

テーマ候補があれば5/3までにここに追加してください

**Comment by matsumotius** [comment]
なお5/3から実作業を開始しますが、忙しければ意見やレビューだけで大丈夫です。

**Comment by matsumotius** [comment]
じゃあとりあえず英単語アプリ作るんでｵﾅｼｬｽ
アプリ名だれか適当に決めて

**Comment by cawara** [comment]
英単GO！・・・は、既にあったのでVomageを提案しときます。

**Comment by matsumotius** [comment]
じゃあそれで

**Comment by matsumotius** [comment]
閉じる
