### ISSUE TITLE
[調査] 英単語で画像検索できるか調べる

### ISSUE THREAD

**Issue by matsumotius** [android-teamdev/vomage#11]
英単語で画像検索して単語の意味がわかるような結果が出るのか調べる
shutterstockなるサービスあったのでAPIアクセス出来るかとか調べる

**Comment by matsumotius** [comment]
shining問題を解決できることが分かった
ちなみにshining問題とはshiningで画像検索すると映画のおっさんが出てくること(光ってたりする画像が欲しい)
単語の後に"shutterstock"と付け加えるだけで解決できた！！すごい

なのでGoogle画像検索API使って何とか取れそう

**Comment by matsumotius** [comment]
Google検索APIしんどかった(1日100アクセスの制限あるらしい)
とりあえずkimono使ってスクレイピング経由で開発用APIつくる

**Comment by cawara** [comment]
Flickr画像検索APIは3600query/hourらしい。

**Comment by matsumotius** [comment]
Flickrだとパーソナルな写真になりそうだけどどうなんだろう
とりあえず今はBingにtryしています

**Comment by cawara** [comment]
> パーソナルな写真

なるほどたしかに

あと、画像読み込み周りはPicassoライブラリが気になります
http://square.github.io/picasso/

**Comment by matsumotius** [comment]
> あと、画像読み込み周りはPicassoライブラリが気になります

いいですね。ぜひ使いましょう。

とりあえずBingはAPI制限的にもコード的にもいけそうでした
https://github.com/rcullito/searchbing でかなり楽に書けます。

これ使ってHerokuでAPIサーバ建てれば画像は即供給できそう。
ということが分かった

**Comment by matsumotius** [comment]
APIキーアプリに埋め込みになるけど
JavaのSDK使えばクライアントだけで完結したのも出来ますね

**Comment by matsumotius** [comment]
大体見当がついたので閉じる
一旦ローカルの犬猫の画像表示まで終わったらWebから取るようにしたい
